config/routes.rb
Rails.application.routes.draw do 
  resources :friend_requests
  get 'password_reset/new'
  post 'password_reset/new', to: "password_reset#create"
  get 'password_reset/edit'

  resources :users do

  resources :friendships do
    resources :messages
  end
   end
  get '/friend', to: "friendships#friend"
  
  resources :sessions
  resources :password_resets
  
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :friendships
   has_many :friends, :through => :friendships

	validates :email,:uname, uniqueness:true, :on=> :create
 
	#validates :password,inclusion: { in: %w( & * $ %) }
     has_many :requested_friendships, -> { where(status: "pending")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :requested_friends, :through => :requested_friendships, :source => :user


   has_many :pending_friendships, -> { where(status: "requested")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :pending_friends, :through => :pending_friendships, :source => :user


   has_many :accepted_friendships, -> { where(status: "accepted")}, :class_name => "Friendship",:foreign_key => "friend_id"
   has_many :accepted_friends, :through => :accepted_friendships, :source => :user

   has_many :conversations
   has_many :exchanges, :through => :conversations

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def new
	@user=User.new
end

def friend
	@users=User.all
end

def index
	@users=User.all
end

def show
	@user=User.find(params[:id])
  @all_users = User.where.not(id: @user.id ) - @user.friends

    @accepted_friends = @user.accepted_friends
    @pending_friends = @user.pending_friends 
    @requested_friends = @user.requested_friends  

end

def create
    @user = User.new(user_params)

    if @user.save
      UserMailer.signup_confirmation(@user).deliver_now
      session[:user_id] = @user.id
      flash[:success] = "Thank you for signing up! You are now logged in."
      redirect_to @user
    else
      render 'new'
    end
  end
  def destroy
  	 @user=User.find(params[friend.id])
  	 @user.destroy
  end
  
  private
  def user_params
  	params.require(:user).permit(:first_name,:last_name,:image,:uname,:email,:password)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
def established_friendship(other_user)
    if current_user.friends.include?(other_user)
      find_friendship(other_user.id)
    else
      find_inversefriendship(other_user.id)
    end
  end

  def find_friendship(other_user_id)
    current_user.friendships.find_by(friend_id: other_user_id)
  end

  def find_inversefriendship(other_user_id)
    current_user.inverse_friendships.find_by(user_id: other_user_id)
  end

  def owner?(user)
    current_user == user
  end

end

app/views/users/index.html.erb
<h1>Welcome to this new Application</h1>
  <%= link_to "Sign Up",new_user_path(@user) %><br>
  <p><%= link_to "SignIn",new_session_path(:user_id) %><p>
  
  

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for :user, url: users_path do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <h1>Create your account</h1>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>

<p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </p>

<p>
    <%= f.label :uname %><br />
    <%= f.text_field :uname %>
  </p>
  <p>
    <%= f.label :email, "Email Address" %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>

  <p><%= f.submit "Sign up" %></p>

<% end %>

app/views/users/show.html.erb
<%if loggedin %>
<h3>Welcome  <%= image_tag(@user.image.url)%><%= @user.first_name  %><%= @user.last_name  %></h3><br>
<h1> My Profile </h1>
<p>
	<strong>Firstname:</strong>
    <%= current_user.first_name %>
</p>
<p>
	<strong>Lastname:</strong>
    <%= @user.last_name %>
</p>
<p>
	<strong>Username:</strong>
    <%= @user.uname %>
</p>
<p>
	<strong>Email:</strong>
    <%= @user.email %>
</p>
<p>
	<strong>Image:</strong>
    <%= image_tag(current_user.image_url) %>
</p>
<table>
     <tr>
    <th>Active Friends</th>
    <th></th>
        </tr><% @accepted_friends.each do |friend| %>
    <tr>
      <td><%= friend.first_name %>  <%= friend.last_name %></td>
      
      <td><%= link_to "Send Messages", new_user_friendship_message_path(@user.id,friend.id) %></td><br>
      <td><%= link_to "Unfriend",user_friendship_path(@user.id,friend.id), :method => :delete, data: { confirm: 'Are you sure?' } %></td><br>
     </tr>
    <% end %> 
   </table>


    <table>
     <tr><br><br>
    <th>Listing Of All Users</th>
    <th></th>
        </tr><% @all_users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= link_to "Send Friend Request", user_friendships_path(:user_id => current_user.id ,:friend_id => user), :method => :post %></td><br>
    </tr>
  <% end %> 
</table>

    <table>
     <tr><br><br>
    <th>Accept Friend Request</th>
    <th></th>
        </tr><% @pending_friends.each do |user| %>
    <tr>
      <td><%= user.first_name %>  <%= user.last_name %></td>
      
      <td><%= link_to "Accept Request", user_friendship_path(@user.id, user.id), :method => :patch %></td><br>
      <td><%= link_to "Decline",  user_friendship_path(@user.id,user.id), :method => :delete,data: { confirm: 'Are you sure?' } %></td><br>
     </tr>
    <% end %> 
   </table>


   <table>
     <tr><br><br>
    <th>Friend Request Sent to</th>
    <th></th>
        </tr><% @requested_friends.each do |user| %>
    <tr>
      <td><%= user.first_name %>  <%= user.last_name %></td>
      
      
     </tr>
    <% end %> 
   </table>

<p><%= link_to "view profile",users_path(@user),:method =>
:get %></p>
<p><%= link_to "LogOut",session_path(current_user), method: :delete %></p>
<%else%>
<h1>login first</h1>
<%= link_to "login", new_session_path %>
<%end%>